# Generated by Django 5.2.9 on 2025-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите свой телеграм chat-id",
                max_length=50,
                null=True,
                verbose_name="Telegram chat-id",
            ),
        ),
    ]
