# Generated by Django 5.2.9 on 2025-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.BigIntegerField(
                blank=True, help_text="Укажите свой телеграм chat-id", null=True, verbose_name="Telegram chat-id"
            ),
        ),
    ]
