# Generated by Django 5.2.9 on 2025-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Europe/Moscow", "Москва"),
                    ("Europe/Kaliningrad", "Калининград"),
                    ("Asia/Yekaterinburg", "Екатеринбург"),
                    ("Asia/Novosibirsk", "Новосибирск"),
                    ("Asia/Krasnoyarsk", "Красноярск"),
                    ("Asia/Irkutsk", "Иркутск"),
                    ("Asia/Yakutsk", "Якутск"),
                    ("Asia/Vladivostok", "Владивосток"),
                    ("Asia/Sakhalin", "Сахалин"),
                    ("Asia/Magadan", "Магадан"),
                    ("Asia/Kamchatka", "Камчатка"),
                ],
                default="Europe/Moscow",
                max_length=32,
            ),
        ),
    ]
