# Generated by Django 5.2.9 on 2025-12-07 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        help_text="Напишите, что планируете сделать (например, поприседать 20 раз)",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите, где: например, дома, в парке и др.",
                        max_length=500,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "habit_time",
                    models.TimeField(blank=True, null=True, verbose_name="Время начала выполнения привычки"),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Например, 1 → каждый день, 2 → раз в два дня (не более семи дней)",
                        verbose_name="Частота выполнения привычки в днях",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Не более 120 секунд",
                        verbose_name="Количество времени для выполнения (в секундах)",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение (если нет связанной приятной привычки)",
                        max_length=500,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Сделать привычку видимой для других пользователей",
                        verbose_name="Публичная привычка",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, выполняемая как вознаграждение (если не указано вознаграждение)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["periodicity", "habit_time"],
                "unique_together": {("user", "action", "place")},
            },
        ),
    ]
